### ISSUE TITLE
Pre-work submission coder school

### ISSUE THREAD

**Issue by hachanuy** [hachanuy/prework_coderschool#2]
Here is my pre-work, there are some problems causing heroku keep showing error 404, i tried to change the route but it doesn't work. Thank you.
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, hachanuy!

 :yum: Everything looks good with the format of your submission. We'll be reviewing your submission soon!

**Comment by hoksilato** [comment]
Hi @hachanuy     

Thanks for your submitting. Good work :thumbsup:.

In summary, your submission is good. Well done with case insensitive searching. But you need to fix some below errors and doing the optional stories will improve your chance of getting in.

- I didn't see the post that introduces the App Creator with name, picture.
- Your "navbar" didn't work. It should be responsive to window size.

Below are some **suggestions** that can improve your app:

- Articles should be displaying with `created_at` descending order.
- You can improve your blog UI with some [Bootstrap 4 examples](http://v4-alpha.getbootstrap.com/examples/).
- For the better performance and UX, you can use `kaminari` gem for pagination.
- Always be cautious with user input, you can view more detail at [Active Record Validations](http://edgeguides.rubyonrails.org/active_record_validations.html).

Let us know if you have any questions.

/cc @coderschoolreview @harley
